public class primitiveTypeTest {
	public static void main(String[] args) {
		//byte类型
		System.out.println("基本类型：byte\n二进制位数："+Byte.SIZE);
		System.out.println("包装类：java.lang.Byte");
		System.out.println("最小值：Byte.MIN_VALUE："+Byte.MIN_VALUE);
		System.out.println("最大值：Byte.MAX_VALUE："+Byte.MAX_VALUE);
		System.out.println();
		//short类型
		System.out.println("基本类型：short\n二进制位数："+Short.SIZE);
		System.out.println("包装类：java.lang.Short");
		System.out.println("最小值：Short.MIN_VALUE："+Short.MIN_VALUE);
		System.out.println("最大值：Short.MAX_VALUE："+Short.MAX_VALUE);
		System.out.println();
		//int类型
		System.out.println("基本类型：int\n二进制位数："+Integer.SIZE);
		System.out.println("包装类：java.lang.Integer");
		System.out.println("最小值：Integer.MIN_VALUE："+Integer.MIN_VALUE);
		System.out.println("最大值：Integer.MAX_VALUE："+Integer.MAX_VALUE);
		System.out.println();
		//long类型
		System.out.println("基本类型：long\n二进制位数："+Long.SIZE);
		System.out.println("包装类：java.lang.Long");
		System.out.println("最小值：Long.MIN_VALUE："+Long.MIN_VALUE);
		System.out.println("最大值：Long.MAX_VALUE："+Long.MAX_VALUE);
		System.out.println();
		//float类型
		System.out.println("基本类型：Float\n二进制位数："+Float.SIZE);
		System.out.println("包装类：java.lang.Float");
		System.out.println("最小值：float.MIN_VALUE："+Float.MIN_VALUE);
		System.out.println("最大值：Float.MAX_VALUE："+Float.MAX_VALUE);
		System.out.println();
		//double类型
		System.out.println("基本类型：double\n二进制位数："+Double.SIZE);
		System.out.println("包装类：java.lang.Double");
		System.out.println("最小值：Double.MIN_VALUE："+Double.MIN_VALUE);
		System.out.println("最大值：Double.MAX_VALUE："+Double.MAX_VALUE);
		System.out.println();
		//char类型
		System.out.println("基本类型：char\n二进制位数："+Character.SIZE);
		System.out.println("包装类：java.lang.Character");
		System.out.println("最小值：Character.MIN_VALUE："+Character.MIN_VALUE);
		System.out.println("最大值：Character.MAX_VALUE："+Character.MAX_VALUE);
		System.out.println();
	}
}
